### ISSUE TITLE
Barometric pressure readings

### ISSUE THREAD

**Issue by aldera123** [bpennypacker/WeatherFlow-Indigo-Plugin#23]
The barometric pressure readings are way off. The Tempest device displays 29.993 inHg and the plugin displays 39.09 inHg. Same problem if I switch units to millibars. Using version 0.2.1.

**Comment by bpennypacker** [comment]
Are you using the plugin via UDP or Websockets? If you're using the Websocket version then what is the Station ID of the station you are using?

**Comment by aldera123** [comment]
Hi Bruce. I’m using UDP. My Station ID is 5509.

I can’t currently create a valid Websocket device. When I try to, and I click on the “Edit Device Settings…” , the “Smart Weather Tempest Websocket Device:” dropdown box is not populated with anything to select. The “State Display:” dropdown box is.










ralph@sabene.com

**Comment by aldera123** [comment]
I forgot to mention that I posted the following on the Indigo website forum page for your plugin:

"I had trouble with getting the data to update correctly in the beginning. I initially created a Tempest UDP device for each weather value I wanted to track and then put them on a control page. They never updated correctly. What I then did was delete all the UDP devices and created a single UDP device with a "blank" value. Then on the control page I used that one device to create values for each weather reading I wanted. Now they update on the page every 60 seconds. I still have the bad pressure reading but everything else is updating correctly." 


ralph@sabene.com



> Begin forwarded message:
> 
> From: "ralph@sabene.com" <ralph@sabene.com>
> Subject: Re: [bpennypacker/WeatherFlow-Indigo-Plugin] Barometric pressure readings (#23)
> Date: July 15, 2020 at 10:49:09 AM EDT
> To: bpennypacker/WeatherFlow-Indigo-Plugin <reply@reply.github.com>
> 
> Hi Bruce. I’m using UDP. My Station ID is 5509.
> 
> I can’t currently create a valid Websocket device. When I try to, and I click on the “Edit Device Settings…” , the “Smart Weather Tempest Websocket Device:” dropdown box is not populated with anything to select. The “State Display:” dropdown box is.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ralph@sabene.com <mailto:ralph@sabene.com>
> 
> 
>

**Comment by bpennypacker** [comment]
Station ID 5509 doesn't appear to be valid, or it's been made private. This URL should be showing a complete weather summary: https://tempestwx.com/station/5509/

Instead it's completely blank. You should be seeing something like this: https://tempestwx.com/station/23707/

5509 seems like a strange ID for a Tempest. Every station ID I've seen has been 5 digits, and smaller values correlate to the first generation AIR/SKY devices, while the newer Tempst has higher values. Can you locate your device on the map at https://tempestwx.com/map/ then click on the icon for it and send the link that it shows at that point?

**Comment by aldera123** [comment]
Sorry,

I gave you the serial number of the unit. The station ID is 21493.



ralph@sabene.com

**Comment by bpennypacker** [comment]
That Station ID seems to be working fine for me. Try going into the plugin settings, enabling Websockets, and using 21493 as your station ID.

**Comment by aldera123** [comment]
Created a Websocket device and the barometric pressure is still the wrong value. It’s returning the same value as the UDP device.



ralph@sabene.com

**Comment by bpennypacker** [comment]
This should now be fixed in v0.2.3. Keep in mind that the readings from the public API may still vary slightly from what you see in the WeatherFlow app. They apparently perform some analysis based on other stations in your geographic area and use that data in their app, which they don't (currently) make available to the public. There's more discussion on this in the comments for #14 if you're interested.

**Comment by aldera123** [comment]
Great. Thanks for fixing it so quickly.



ralph@sabene.com

**Comment by aldera123** [comment]
Hi Bruce,

I just installed the v0.2.3. The Tempest device is showing 30.00 inHg and your plugin is showing 29.33. That’s still a pretty big difference even allowing for a little variation.



ralph@sabene.com

**Comment by bpennypacker** [comment]
Please enable debugging in the plugin configuration (check the box at the bottom of the settings). The Event Log should start logging the UDP data being received by your Tempest, and should look something like this (formatting may be a bit different):

    {
	"serial_number": "ST-00006839",
	"type": "obs_st",
	"hub_sn": "HB-00019566",
	"obs": [
		[1591904071, 0.36, 1.97, 3.17, 230, 3, 1015.44, 19.16, 97.13, 13664, 0.47, 114, 0.127551, 1, 0, 0, 2.561, 1]
	],
	"firmware_revision": 129
    }

The pressure, in MB, is the 7th number in that "obs" list. So in the above example it's 1015.44. If you set the plug-in to use millibars for pressure readings then you should see this same value being reported by the plug-in. To convert from millibars to inches of mercury you multiply by 0.02953, so this example should show approx. 29.98592601 inHg. That's what the plug-in should report in this case.

According to [this post](https://community.weatherflow.com/t/pressure-display-station-vs-sea-level/482) on the WeatherFlow site, their website & apps calculate and display the pressure at sea level since any time you see/hear weather reports from other sources the pressure is always provided at sea level. So unless your device is set to an elevation of 0 feet it sounds like you should expect the raw results and what you see in their app be a bit different. Even if you do set it to 0 elevation there's still a chance the results in the WeatherFlow apps will differ from the raw data the plug-in provides given that they do some analysis of the data. Unfortunately WeatherFlow doesn't currently provide API access to the calculated sea-level pressure or any of the other modified results that their apps rely upon. (Again, see the discussion in #14 regarding non-public data, forecast data, etc.)

**Comment by aldera123** [comment]
Okay. Thanks, Bruce. If I set my elevation to 0 feet it does show the station pressure of 29.34 in the WeatherFlow app instead of the sea level pressure of 30.01.

Thanks again for the help.



ralph@sabene.com

**Comment by bpennypacker** [comment]
Glad to help!
