### ISSUE TITLE
Misspelling error

### ISSUE THREAD

**Issue by jrickmd** [bpennypacker/WeatherFlow-Indigo-Plugin#26]
0.2.3 gives me an error

> device "WeatherFlow" state key last_strike_formatted not defined (ignoring update request)

in the custom device states it is misspelled last_srike_formatted

Rick

**Comment by bpennypacker** [comment]
Rick,

I actually fixed that typo in v0.2.1 of the plug-in. Unfortunately existing devices don't update themselves automatically when the XML that defines an existing state (in Devices.xml) changes. The easiest way to deal with this, unfortunately, is to delete the device in question and then re-add it.

In the meantime, I did just come across the following comment in one of the Indigo forums. I'll try to dig into this and see if I can figure out how to do it so that the plug-in handles this properly in the future.

> Old devices won't get updated to changes in the Devices.xml unless you do a specific API call. Which I can't remember off the top of my head.

**Comment by jrickmd** [comment]
Wondered when I saw that in the release notes…

I did go into that device. Clicked Device Settings. Reselected the item from the Tempest drop down, clicked Save and got

   SQL Logger                      adding column "last_strike_formatted" to table device_history_367014068 ("WeatherFlow")

In the Log.

Success!

**Comment by bpennypacker** [comment]
Awesome!
