### ISSUE TITLE
Version 0.3.0

### ISSUE THREAD

**Issue by jltnol** [bpennypacker/WeatherFlow-Indigo-Plugin#31]
Just just did the upgrade to the latest version of the plugin... managed to get my "token", (I'm assuming any text entered will create a valid token), but now this is the error message I get every 10 seconds:

```
WeatherFlow Smart Weather Error Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 718, in runConcurrentThread
  File "plugin.py", line 646, in _process_message
  File "plugin.py", line 849, in process_obs_tempest
KeyError: 'key mode not found in dict'

   WeatherFlow Smart Weather Error plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
```

Aside from the error message, I THINK it is working as it should in Indigo... jut a bit early to tell......And I don't see anything else on the config page that might cause an issue.  I do have both UDP and Websocket enabled.

And your instructions to get both the Token and the station ID(which I already had), were PERFECT!  Thank you for making it so easy.

ALSO:  I don't know who is responsible for this but "View Wiki" link at the bottom of the config page doesn't work.  Not sure if this is a plugin problem, or an Indigo one.. but... just wanted to mention it.

**Comment by bpennypacker** [comment]
> KeyError: 'key mode not found in dict'

"mode" is a new state that was added to the plug-in. I vaguely recall there may be something I need to do to make existing instances of the plug-in recognize it. I'll see about getting an update for this ASAP.

Glad to hear the documentation is clear. Having done everything from tech support to professional software development it's one thing I've always tried to ensure is done well since good documentation typically translates to fewer support headaches.

And thanks for the pointer about the wiki link. I'll see what needs to be done there as well...

**Comment by bpennypacker** [comment]
Give [v0.3.1](/bpennypacker/WeatherFlow-Indigo-Plugin/releases/tag/v0.3.1) a try. It should ensure Indigo starts to see the "mode" state on the websocket devices now.

It turns out that the code to launch a web browser & web page only works when running the Indigo client on the server itself. It won't launch if you're running the client on a different system than the server. So I removed that wiki button and instead added a note to just click on the question mark at the bottom of the configuration dialog since it does launch the wiki page properly whether you're running on the server or not.

**Comment by jltnol** [comment]
So you are right about the client/ server… I was definitely on a different computer running the client, but the ? fixes everything.

I’ve downloaded the latest version, and so far, no Red Ink in the Event Log.

Thanks ever so much for taking time to look into this.

REALLY appreciate it.. :) 

 Cheers

 Jeffrey

**Comment by bpennypacker** [comment]
Awesome, glad to hear it!
